Use Django management CommandError to eliminate the traceback on error
Instead of the long traceback, the error now looks like:

    Schema generation summary:
    Warnings: 4 (1 unique)
    Errors:   0 (0 unique)

    SchemaValidationError: Failing as requested due to warnings