fix: avoid circular import of/via rest_framework's APIView
The typing hints added in 9819424 caused a regression with version
0.17.1, where importing `OpenApiAuthenticationExtension` from
`drf_spectacular.extensions` might cause a circular import error:

> ImportError: Could not import
> 'project.app.authentication.MyAuthentication' for API setting
> 'DEFAULT_AUTHENTICATION_CLASSES'. ImportError: cannot import name
> 'OpenApiAuthenticationExtension' from partially initialized module
> 'drf_spectacular.extensions' (most likely due to a circular import)
> (…/.venv/lib/python3.9/site-packages/drf_spectacular/extensions.py).